# Copyright (c) 2026 Noah Severs
# SPDX-License-Identifier: LicenseRef-Proprietary
"""Generate ui/static/currency-guess.js: the setup form's currency suggestion.

The setup form suggests a currency from where the browser is: the country of the
browser's timezone first, then the region of its language, then nothing. Both
lookups are static tables committed in the repo, because desktop installs on
Windows and macOS have no system zone.tab to read at runtime.

    python3 scripts/gen_currency_guess.py [path/to/zoneinfo]

Needs the ``babel`` package (CLDR territory currencies) and a tzdata directory with
``zone.tab`` and ``tzdata.zi`` (default /usr/share/zoneinfo). Run it again only to
refresh the tables.

Browsers built on ICU (Chrome, Edge, the desktop app) report some zones by their old
names, such as Asia/Calcutta or America/Buenos_Aires. Servers whose tzdata leaves the
old names out cannot load them, and zone.tab does not list them, so the script also
maps each old name to the zone it now links to.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from babel.numbers import get_territory_currencies

OUT = Path(__file__).resolve().parents[1] / "ui" / "static" / "currency-guess.js"


def zone_countries(zone_tab: Path) -> dict[str, str]:
    """IANA zone -> ISO 3166 country code, from tzdata's zone.tab."""
    zones: dict[str, str] = {}
    for line in zone_tab.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        country, _coords, zone = line.split("\t")[:3]
        zones[zone] = country
    return dict(sorted(zones.items()))


def zone_links(tzdata_zi: Path, zones: dict[str, str]) -> dict[str, str]:
    """Old zone name -> the zone.tab zone it links to, for names zone.tab leaves out."""
    links: dict[str, str] = {}
    for line in tzdata_zi.read_text().splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[0] == "L" and parts[2] not in zones and parts[1] in zones:
            links[parts[2]] = parts[1]
    return dict(sorted(links.items()))


def country_currencies(countries: set[str]) -> dict[str, str]:
    """ISO 3166 country code -> the currency CLDR says is legal tender there today."""
    out: dict[str, str] = {}
    for country in sorted(countries):
        current = get_territory_currencies(country, tender=True)
        if current:
            out[country] = current[0]
    return out


def main() -> None:
    zoneinfo = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/usr/share/zoneinfo")
    zones = zone_countries(zoneinfo / "zone.tab")
    links = zone_links(zoneinfo / "tzdata.zi", zones)
    # Language regions reach countries no timezone names (e.g. a "-419" region is
    # numeric and ignored), so the currency table covers every CLDR territory with
    # a two-letter code, not only the ones zone.tab lists.
    from babel.core import get_global
    territories = {code for code in get_global("territory_currencies") if len(code) == 2 and code.isalpha()}
    currencies = country_currencies(territories | set(zones.values()))
    body = (
        "// Generated by scripts/gen_currency_guess.py - do not edit by hand.\n"
        "// Suggests a currency from where the browser is: the timezone's country first,\n"
        "// then the language region, else nothing. Also gives the current name of a zone\n"
        "// the browser reports by an old one.\n"
        "(function () {\n"
        f"  var ZONE_COUNTRY = {json.dumps(zones, separators=(',', ':'))};\n"
        f"  var ZONE_LINK = {json.dumps(links, separators=(',', ':'))};\n"
        f"  var COUNTRY_CURRENCY = {json.dumps(currencies, separators=(',', ':'))};\n"
        "  function region(lang) {\n"
        "    var parts = String(lang || '').split(/[-_]/);\n"
        "    for (var i = 1; i < parts.length; i++) {\n"
        "      if (/^[A-Za-z]{2}$/.test(parts[i])) return parts[i].toUpperCase();\n"
        "    }\n"
        "    return '';\n"
        "  }\n"
        "  window.celerpCurrentZone = function (timeZone) {\n"
        "    return ZONE_LINK[timeZone || ''] || timeZone || '';\n"
        "  };\n"
        "  window.celerpGuessCurrency = function (timeZone, languages) {\n"
        "    var country = ZONE_COUNTRY[window.celerpCurrentZone(timeZone)];\n"
        "    if (country && COUNTRY_CURRENCY[country]) return COUNTRY_CURRENCY[country];\n"
        "    var langs = languages || [];\n"
        "    for (var i = 0; i < langs.length; i++) {\n"
        "      var r = region(langs[i]);\n"
        "      if (r && COUNTRY_CURRENCY[r]) return COUNTRY_CURRENCY[r];\n"
        "    }\n"
        "    return '';\n"
        "  };\n"
        "})();\n"
    )
    OUT.write_text(body)


if __name__ == "__main__":
    main()
