# Copyright (c) 2026 Noah Severs
# SPDX-License-Identifier: LicenseRef-Proprietary
"""Generate ui/static/currency-guess.js: the setup form's currency suggestion.

The setup form suggests a currency from where the browser is: the country of the
browser's timezone first, then the region of its language, then nothing. Both
lookups are static tables committed in the repo, because desktop installs on
Windows and macOS have no system zone.tab to read at runtime.

    python3 scripts/gen_currency_guess.py [path/to/zone.tab]

Needs the ``babel`` package (CLDR territory currencies) and a tzdata ``zone.tab``
(default /usr/share/zoneinfo/zone.tab). Run it again only to refresh the tables.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from babel.numbers import get_territory_currencies

OUT = Path(__file__).resolve().parents[1] / "ui" / "static" / "currency-guess.js"


def zone_countries(zone_tab: Path) -> dict[str, str]:
    """IANA zone -> ISO 3166 country code, from tzdata's zone.tab."""
    zones: dict[str, str] = {}
    for line in zone_tab.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        country, _coords, zone = line.split("\t")[:3]
        zones[zone] = country
    return dict(sorted(zones.items()))


def country_currencies(countries: set[str]) -> dict[str, str]:
    """ISO 3166 country code -> the currency CLDR says is legal tender there today."""
    out: dict[str, str] = {}
    for country in sorted(countries):
        current = get_territory_currencies(country, tender=True)
        if current:
            out[country] = current[0]
    return out


def main() -> None:
    zone_tab = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/usr/share/zoneinfo/zone.tab")
    zones = zone_countries(zone_tab)
    # Language regions reach countries no timezone names (e.g. a "-419" region is
    # numeric and ignored), so the currency table covers every CLDR territory with
    # a two-letter code, not only the ones zone.tab lists.
    from babel.core import get_global
    territories = {code for code in get_global("territory_currencies") if len(code) == 2 and code.isalpha()}
    currencies = country_currencies(territories | set(zones.values()))
    body = (
        "// Generated by scripts/gen_currency_guess.py - do not edit by hand.\n"
        "// Suggests a currency from where the browser is: the timezone's country first,\n"
        "// then the language region, else nothing.\n"
        "(function () {\n"
        f"  var ZONE_COUNTRY = {json.dumps(zones, separators=(',', ':'))};\n"
        f"  var COUNTRY_CURRENCY = {json.dumps(currencies, separators=(',', ':'))};\n"
        "  function region(lang) {\n"
        "    var parts = String(lang || '').split(/[-_]/);\n"
        "    for (var i = 1; i < parts.length; i++) {\n"
        "      if (/^[A-Za-z]{2}$/.test(parts[i])) return parts[i].toUpperCase();\n"
        "    }\n"
        "    return '';\n"
        "  }\n"
        "  window.celerpGuessCurrency = function (timeZone, languages) {\n"
        "    var country = ZONE_COUNTRY[timeZone || ''];\n"
        "    if (country && COUNTRY_CURRENCY[country]) return COUNTRY_CURRENCY[country];\n"
        "    var langs = languages || [];\n"
        "    for (var i = 0; i < langs.length; i++) {\n"
        "      var r = region(langs[i]);\n"
        "      if (r && COUNTRY_CURRENCY[r]) return COUNTRY_CURRENCY[r];\n"
        "    }\n"
        "    return '';\n"
        "  };\n"
        "})();\n"
    )
    OUT.write_text(body)


if __name__ == "__main__":
    main()
