# Copyright (c) 2026 Noah Severs
# SPDX-License-Identifier: BSL-1.1

"""Demo data seeding for new companies.

Seeds vertical-aware demo items so new users see a working UI immediately.
All demo records carry source="demo" and are auto-wiped on first successful
import of that entity type.
"""

from __future__ import annotations

import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from celerp.events.engine import emit_event


_DEMO_USER_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")  # sentinel, not a real user

# Generic demo items (no vertical / blank vertical)
# Prices use price list names as keys (e.g. "Retail", "Wholesale", "Cost").
# These are emitted as item.pricing.set events during seeding.
_GENERIC_ITEMS: list[dict] = [
    {
        "sku": "DEMO-001",
        "name": "[DEMO] Sample Item",
        "category": "General",
        "quantity": 10,
        "sell_by": "piece",
        "prices": {"Retail": 19.99, "Wholesale": 14.99, "Cost": 9.99},
        "status": "available",
        "description": "This is a demo item. It will be removed when you import your first CSV.",
        "barcode": "2000010000013",
        "attributes": {},
    },
]

# Vertical-specific demo items keyed by preset name
_VERTICAL_ITEMS: dict[str, list[dict]] = {
    "agricultural": [
        {
            "sku": "DEMO-AGR-001",
            "name": "[DEMO] Jasmine Rice - 25kg bag",
            "category": "grain_cereal",
            "quantity": 50,
            "sell_by": "piece",
            "prices": {"Retail": 32.00, "Wholesale": 22.00, "Cost": 14.00},
            "status": "available",
            "description": "[DEMO] Jasmine rice 25kg bag. Remove before going live.",
            "barcode": "2010010012503",
            "attributes": {"variety": "Jasmine", "origin": "Thailand", "moisture_pct": "14"},
        },
        {
            "sku": "DEMO-AGR-002",
            "name": "[DEMO] Cherry Tomatoes - 1kg punnet",
            "category": "fresh_produce",
            "quantity": 100,
            "sell_by": "piece",
            "prices": {"Retail": 3.50, "Wholesale": 2.20, "Cost": 1.40},
            "status": "available",
            "description": "[DEMO] Fresh cherry tomatoes 1kg punnet. Remove before going live.",
            "barcode": "2010020010012",
            "attributes": {"variety": "Cherry", "grade": "Class I", "origin": "Local"},
        },
        {
            "sku": "DEMO-AGR-003",
            "name": "[DEMO] NPK Fertilizer 15-15-15 - 50kg bag",
            "category": "fertilizer_chemical",
            "quantity": 20,
            "sell_by": "piece",
            "prices": {"Retail": 28.00, "Wholesale": 20.00, "Cost": 12.50},
            "status": "available",
            "description": "[DEMO] Balanced NPK fertilizer 50kg. Remove before going live.",
            "barcode": "2010030050003",
            "attributes": {"npk_ratio": "15-15-15", "form": "Granular", "weight_kg": "50"},
        },
        {
            "sku": "DEMO-AGR-004",
            "name": "[DEMO] Sunflower Seeds - 20kg bag",
            "category": "seeds",
            "quantity": 30,
            "sell_by": "piece",
            "prices": {"Retail": 45.00, "Wholesale": 30.00, "Cost": 18.00},
            "status": "available",
            "description": "[DEMO] High-yield sunflower seeds 20kg. Remove before going live.",
            "barcode": "2010040020004",
            "attributes": {"variety": "High-Oleic", "germination_pct": "95", "weight_kg": "20"},
        },
    ],
    "artwork": [
        {
            "sku": "DEMO-ART-001",
            "name": "[DEMO] Oil on Canvas - Abstract Landscape",
            "category": "painting",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 4500.00, "Wholesale": 3000.00, "Cost": 800.00},
            "status": "available",
            "description": "[DEMO] Original oil painting on canvas. Remove before going live.",
            "barcode": "2020010001001",
            "attributes": {"medium": "Oil on Canvas", "dimensions_cm": "90 x 120", "year": "2024"},
        },
        {
            "sku": "DEMO-ART-002",
            "name": "[DEMO] Bronze Sculpture - Figure Study",
            "category": "sculpture",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 12000.00, "Wholesale": 8000.00, "Cost": 3500.00},
            "status": "available",
            "description": "[DEMO] Limited edition bronze sculpture. Remove before going live.",
            "barcode": "2020020001002",
            "attributes": {"material": "Bronze", "edition": "3/12", "height_cm": "45"},
        },
        {
            "sku": "DEMO-ART-003",
            "name": "[DEMO] Signed Lithograph Print - Edition 5/50",
            "category": "print_edition",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 850.00, "Wholesale": 550.00, "Cost": 200.00},
            "status": "available",
            "description": "[DEMO] Signed limited edition lithograph. Remove before going live.",
            "barcode": "2020030001003",
            "attributes": {"technique": "Lithograph", "edition": "5/50", "dimensions_cm": "60 x 80"},
        },
        {
            "sku": "DEMO-ART-004",
            "name": "[DEMO] Fine Art Photography - Archival Print",
            "category": "art_photography",
            "quantity": 3,
            "sell_by": "piece",
            "prices": {"Retail": 1200.00, "Wholesale": 780.00, "Cost": 300.00},
            "status": "available",
            "description": "[DEMO] Archival pigment print, framed. Remove before going live.",
            "barcode": "2020040001004",
            "attributes": {"print_type": "Archival Pigment", "edition": "2/10", "dimensions_cm": "70 x 90"},
        },
    ],
    "automotive": [
        {
            "sku": "DEMO-AUTO-001",
            "name": "[DEMO] Front Brake Pad Set - OEM Grade",
            "category": "brake_suspension",
            "quantity": 20,
            "sell_by": "piece",
            "prices": {"Retail": 65.00, "Wholesale": 42.00, "Cost": 22.00},
            "status": "available",
            "description": "[DEMO] Front brake pad set, fits most sedans. Remove before going live.",
            "barcode": "2030010000015",
            "attributes": {"grade": "OEM", "position": "Front", "material": "Semi-Metallic"},
        },
        {
            "sku": "DEMO-AUTO-002",
            "name": "[DEMO] Engine Oil Filter - Universal",
            "category": "engine_part",
            "quantity": 50,
            "sell_by": "piece",
            "prices": {"Retail": 12.00, "Wholesale": 7.50, "Cost": 3.80},
            "status": "available",
            "description": "[DEMO] Universal engine oil filter. Remove before going live.",
            "barcode": "2030020000026",
            "attributes": {"thread_size": "M20x1.5", "compatibility": "Universal", "micron": "25"},
        },
        {
            "sku": "DEMO-AUTO-003",
            "name": "[DEMO] 205/55R16 All-Season Tire",
            "category": "tire_wheel",
            "quantity": 8,
            "sell_by": "piece",
            "prices": {"Retail": 120.00, "Wholesale": 82.00, "Cost": 55.00},
            "status": "available",
            "description": "[DEMO] All-season tire 205/55R16. Remove before going live.",
            "barcode": "2030030000037",
            "attributes": {"size": "205/55R16", "season": "All-Season", "load_index": "91"},
        },
        {
            "sku": "DEMO-AUTO-004",
            "name": "[DEMO] 5W-30 Synthetic Engine Oil - 5L",
            "category": "fluid_lubricant",
            "quantity": 30,
            "sell_by": "piece",
            "prices": {"Retail": 38.00, "Wholesale": 25.00, "Cost": 14.00},
            "status": "available",
            "description": "[DEMO] Full synthetic 5W-30 engine oil 5L. Remove before going live.",
            "barcode": "2030040000048",
            "attributes": {"viscosity": "5W-30", "type": "Full Synthetic", "volume_l": "5"},
        },
    ],
    "blank": [
        {
            "sku": "DEMO-BLK-001",
            "name": "[DEMO] Custom Service Item A",
            "category": "General",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 100.00, "Wholesale": 75.00, "Cost": 50.00},
            "status": "available",
            "description": "[DEMO] Generic service placeholder. Remove before going live.",
            "barcode": "2040010000010",
            "attributes": {"unit": "hour", "type": "Service"},
        },
        {
            "sku": "DEMO-BLK-002",
            "name": "[DEMO] Custom Product Item B",
            "category": "General",
            "quantity": 10,
            "sell_by": "piece",
            "prices": {"Retail": 50.00, "Wholesale": 35.00, "Cost": 20.00},
            "status": "available",
            "description": "[DEMO] Generic product placeholder. Remove before going live.",
            "barcode": "2040020000027",
            "attributes": {"unit": "piece", "type": "Product"},
        },
        {
            "sku": "DEMO-BLK-003",
            "name": "[DEMO] Custom Bundle Item C",
            "category": "General",
            "quantity": 5,
            "sell_by": "piece",
            "prices": {"Retail": 200.00, "Wholesale": 140.00, "Cost": 80.00},
            "status": "available",
            "description": "[DEMO] Generic bundle placeholder. Remove before going live.",
            "barcode": "2040030000034",
            "attributes": {"unit": "bundle", "type": "Bundle"},
        },
    ],
    "books_media": [
        {
            "sku": "DEMO-BKS-001",
            "name": "[DEMO] Business Management Textbook",
            "category": "book",
            "quantity": 25,
            "sell_by": "piece",
            "prices": {"Retail": 49.99, "Wholesale": 32.00, "Cost": 18.00},
            "status": "available",
            "description": "[DEMO] Business management textbook, hardcover. Remove before going live.",
            "barcode": "2050010000016",
            "attributes": {"format": "Hardcover", "pages": "480", "language": "English"},
        },
        {
            "sku": "DEMO-BKS-002",
            "name": "[DEMO] Classic Rock Vinyl LP",
            "category": "music_vinyl",
            "quantity": 10,
            "sell_by": "piece",
            "prices": {"Retail": 29.99, "Wholesale": 18.00, "Cost": 9.00},
            "status": "available",
            "description": "[DEMO] 180g vinyl LP record. Remove before going live.",
            "barcode": "2050020000023",
            "attributes": {"format": "12-inch LP", "pressing": "180g", "genre": "Classic Rock"},
        },
        {
            "sku": "DEMO-BKS-003",
            "name": "[DEMO] Action RPG Video Game - Standard Edition",
            "category": "video_game",
            "quantity": 15,
            "sell_by": "piece",
            "prices": {"Retail": 59.99, "Wholesale": 40.00, "Cost": 25.00},
            "status": "available",
            "description": "[DEMO] Action RPG game, standard edition. Remove before going live.",
            "barcode": "2050030000030",
            "attributes": {"platform": "PlayStation 5", "rating": "PEGI 18", "region": "PAL"},
        },
        {
            "sku": "DEMO-BKS-004",
            "name": "[DEMO] Sports Trading Card Pack - 12 cards",
            "category": "trading_card",
            "quantity": 100,
            "sell_by": "piece",
            "prices": {"Retail": 8.99, "Wholesale": 5.50, "Cost": 2.80},
            "status": "available",
            "description": "[DEMO] Sports trading card pack, 12 cards. Remove before going live.",
            "barcode": "2050040000047",
            "attributes": {"sport": "Basketball", "cards_per_pack": "12", "series": "2024"},
        },
    ],
    "coins_precious_metals": [
        {
            "sku": "DEMO-CPM-001",
            "name": "[DEMO] 1oz Gold Bullion Bar - 999.9 Fine",
            "category": "gold_bullion",
            "quantity": 5,
            "sell_by": "piece",
            "prices": {"Retail": 2050.00, "Wholesale": 1980.00, "Cost": 1920.00},
            "status": "available",
            "description": "[DEMO] 1 troy oz gold bar, 999.9 fine. Remove before going live.",
            "barcode": "2060010000015",
            "attributes": {"purity": "999.9", "weight_oz": "1", "mint": "PAMP Suisse"},
        },
        {
            "sku": "DEMO-CPM-002",
            "name": "[DEMO] 10oz Silver Bullion Bar - 999 Fine",
            "category": "silver_bullion",
            "quantity": 20,
            "sell_by": "piece",
            "prices": {"Retail": 290.00, "Wholesale": 270.00, "Cost": 255.00},
            "status": "available",
            "description": "[DEMO] 10 troy oz silver bar, 999 fine. Remove before going live.",
            "barcode": "2060020000022",
            "attributes": {"purity": "999", "weight_oz": "10", "mint": "Sunshine Mint"},
        },
        {
            "sku": "DEMO-CPM-003",
            "name": "[DEMO] American Eagle Gold Coin - 1oz 2024",
            "category": "bullion_coin",
            "quantity": 3,
            "sell_by": "piece",
            "prices": {"Retail": 2150.00, "Wholesale": 2050.00, "Cost": 1980.00},
            "status": "available",
            "description": "[DEMO] 2024 American Eagle 1oz gold bullion coin. Remove before going live.",
            "barcode": "2060030000039",
            "attributes": {"purity": "916.7", "year": "2024", "country": "USA"},
        },
        {
            "sku": "DEMO-CPM-004",
            "name": "[DEMO] Morgan Silver Dollar 1881-S MS65",
            "category": "numismatic_coin",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 850.00, "Wholesale": 650.00, "Cost": 480.00},
            "status": "available",
            "description": "[DEMO] 1881-S Morgan Silver Dollar graded MS65. Remove before going live.",
            "barcode": "2060040000046",
            "attributes": {"year": "1881", "mint_mark": "S", "grade": "MS65"},
        },
    ],
    "consulting": [
        {
            "sku": "DEMO-CON-001",
            "name": "[DEMO] Strategy Consulting - Day Rate",
            "category": "consulting_service",
            "quantity": 10,
            "sell_by": "piece",
            "prices": {"Retail": 2500.00, "Wholesale": 2000.00, "Cost": 1200.00},
            "status": "available",
            "description": "[DEMO] Senior consultant day rate. Remove before going live.",
            "barcode": "2070010000014",
            "attributes": {"unit": "day", "seniority": "Senior", "discipline": "Strategy"},
        },
        {
            "sku": "DEMO-CON-002",
            "name": "[DEMO] IT Consulting - Hourly Rate",
            "category": "consulting_service",
            "quantity": 40,
            "sell_by": "piece",
            "prices": {"Retail": 180.00, "Wholesale": 140.00, "Cost": 80.00},
            "status": "available",
            "description": "[DEMO] IT consultant hourly rate. Remove before going live.",
            "barcode": "2070020000021",
            "attributes": {"unit": "hour", "seniority": "Mid-level", "discipline": "IT"},
        },
        {
            "sku": "DEMO-CON-003",
            "name": "[DEMO] Project Management - Fixed Fee Package",
            "category": "consulting_service",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 15000.00, "Wholesale": 12000.00, "Cost": 7000.00},
            "status": "available",
            "description": "[DEMO] Fixed-fee project management engagement. Remove before going live.",
            "barcode": "2070030000038",
            "attributes": {"unit": "project", "duration_weeks": "12", "discipline": "PMO"},
        },
    ],
    "cosmetics": [
        {
            "sku": "DEMO-COS-001",
            "name": "[DEMO] Vitamin C Serum - 30ml",
            "category": "skincare",
            "quantity": 40,
            "sell_by": "piece",
            "prices": {"Retail": 45.00, "Wholesale": 28.00, "Cost": 12.00},
            "status": "available",
            "description": "[DEMO] Brightening Vitamin C face serum 30ml. Remove before going live.",
            "barcode": "2080010000013",
            "attributes": {"volume_ml": "30", "key_ingredient": "Vitamin C 15%", "skin_type": "All"},
        },
        {
            "sku": "DEMO-COS-002",
            "name": "[DEMO] Matte Liquid Lipstick - Shade 07",
            "category": "makeup",
            "quantity": 60,
            "sell_by": "piece",
            "prices": {"Retail": 22.00, "Wholesale": 13.00, "Cost": 5.50},
            "status": "available",
            "description": "[DEMO] Long-wear matte liquid lipstick, shade 07 Rose. Remove before going live.",
            "barcode": "2080020000020",
            "attributes": {"shade": "07 Rose", "finish": "Matte", "volume_ml": "5"},
        },
        {
            "sku": "DEMO-COS-003",
            "name": "[DEMO] Argan Oil Hair Mask - 250ml",
            "category": "haircare",
            "quantity": 30,
            "sell_by": "piece",
            "prices": {"Retail": 28.00, "Wholesale": 17.00, "Cost": 7.50},
            "status": "available",
            "description": "[DEMO] Deep conditioning argan oil hair mask 250ml. Remove before going live.",
            "barcode": "2080030000037",
            "attributes": {"volume_ml": "250", "hair_type": "Dry/Damaged", "key_ingredient": "Argan Oil"},
        },
        {
            "sku": "DEMO-COS-004",
            "name": "[DEMO] Floral Eau de Parfum - 50ml",
            "category": "fragrance",
            "quantity": 20,
            "sell_by": "piece",
            "prices": {"Retail": 95.00, "Wholesale": 58.00, "Cost": 25.00},
            "status": "available",
            "description": "[DEMO] Floral EDP fragrance 50ml. Remove before going live.",
            "barcode": "2080040000044",
            "attributes": {"volume_ml": "50", "concentration": "EDP", "notes": "Rose, Jasmine, Musk"},
        },
    ],
    "electronics": [
        {
            "sku": "DEMO-ELEC-001",
            "name": "[DEMO] 15.6-inch Laptop - Core i7 / 16GB / 512GB SSD",
            "category": "laptop",
            "quantity": 5,
            "sell_by": "piece",
            "prices": {"Retail": 1199.00, "Wholesale": 920.00, "Cost": 680.00},
            "status": "available",
            "description": "[DEMO] 15.6-inch laptop, i7 16GB 512GB SSD. Remove before going live.",
            "barcode": "2090010000018",
            "attributes": {"cpu": "Intel Core i7", "ram_gb": "16", "storage": "512GB SSD"},
        },
        {
            "sku": "DEMO-ELEC-002",
            "name": "[DEMO] Smartphone - 256GB Midnight Black",
            "category": "mobile_phone",
            "quantity": 10,
            "sell_by": "piece",
            "prices": {"Retail": 899.00, "Wholesale": 680.00, "Cost": 480.00},
            "status": "available",
            "description": "[DEMO] 6.7-inch smartphone 256GB, midnight black. Remove before going live.",
            "barcode": "2090020000025",
            "attributes": {"storage_gb": "256", "color": "Midnight Black", "network": "5G"},
        },
        {
            "sku": "DEMO-ELEC-003",
            "name": "[DEMO] True Wireless Earbuds with ANC",
            "category": "audio_equipment",
            "quantity": 15,
            "sell_by": "piece",
            "prices": {"Retail": 149.00, "Wholesale": 95.00, "Cost": 52.00},
            "status": "available",
            "description": "[DEMO] True wireless earbuds with active noise cancellation. Remove before going live.",
            "barcode": "2090030000032",
            "attributes": {"battery_hrs": "8+24", "anc": "Yes", "connectivity": "Bluetooth 5.3"},
        },
        {
            "sku": "DEMO-ELEC-004",
            "name": "[DEMO] 55-inch 4K OLED TV",
            "category": "tv_display",
            "quantity": 3,
            "sell_by": "piece",
            "prices": {"Retail": 1499.00, "Wholesale": 1100.00, "Cost": 750.00},
            "status": "available",
            "description": "[DEMO] 55-inch 4K OLED smart TV. Remove before going live.",
            "barcode": "2090040000049",
            "attributes": {"screen_size": "55-inch", "resolution": "4K OLED", "smart": "Yes"},
        },
        {
            "sku": "DEMO-ELEC-005",
            "name": "[DEMO] Gaming Console - Standard Edition",
            "category": "gaming_console",
            "quantity": 4,
            "sell_by": "piece",
            "prices": {"Retail": 499.00, "Wholesale": 390.00, "Cost": 280.00},
            "status": "available",
            "description": "[DEMO] Next-gen gaming console standard edition. Remove before going live.",
            "barcode": "2090050000056",
            "attributes": {"storage_gb": "825", "generation": "Current", "optical_drive": "Yes"},
        },
    ],
    "fashion": [
        {
            "sku": "DEMO-FSH-001",
            "name": "[DEMO] Classic White Oxford Shirt - Size M",
            "category": "tops",
            "quantity": 30,
            "sell_by": "piece",
            "prices": {"Retail": 79.00, "Wholesale": 48.00, "Cost": 22.00},
            "status": "available",
            "description": "[DEMO] Classic white cotton oxford shirt size M. Remove before going live.",
            "barcode": "2100010000015",
            "attributes": {"size": "M", "material": "100% Cotton", "fit": "Regular"},
        },
        {
            "sku": "DEMO-FSH-002",
            "name": "[DEMO] Slim-Fit Chino Trousers - Navy 32/32",
            "category": "bottoms",
            "quantity": 20,
            "sell_by": "piece",
            "prices": {"Retail": 89.00, "Wholesale": 55.00, "Cost": 25.00},
            "status": "available",
            "description": "[DEMO] Navy slim-fit chinos 32/32. Remove before going live.",
            "barcode": "2100020000022",
            "attributes": {"size": "32/32", "color": "Navy", "material": "98% Cotton 2% Elastane"},
        },
        {
            "sku": "DEMO-FSH-003",
            "name": "[DEMO] Leather Sneakers - White Size 42",
            "category": "footwear",
            "quantity": 12,
            "sell_by": "piece",
            "prices": {"Retail": 145.00, "Wholesale": 90.00, "Cost": 48.00},
            "status": "available",
            "description": "[DEMO] White leather low-top sneakers size 42. Remove before going live.",
            "barcode": "2100030000039",
            "attributes": {"size_eu": "42", "color": "White", "material": "Full Grain Leather"},
        },
        {
            "sku": "DEMO-FSH-004",
            "name": "[DEMO] Structured Tote Bag - Tan",
            "category": "bag_handbag",
            "quantity": 8,
            "sell_by": "piece",
            "prices": {"Retail": 220.00, "Wholesale": 135.00, "Cost": 65.00},
            "status": "available",
            "description": "[DEMO] Structured tan leather tote bag. Remove before going live.",
            "barcode": "2100040000046",
            "attributes": {"color": "Tan", "material": "Vegan Leather", "dimensions_cm": "35 x 28 x 12"},
        },
    ],
    "food_beverage": [
        {
            "sku": "DEMO-F&B-001",
            "name": "[DEMO] Cold Brew Coffee - 330ml Can",
            "category": "beverage_nonalc",
            "quantity": 144,
            "sell_by": "piece",
            "prices": {"Retail": 3.50, "Wholesale": 2.10, "Cost": 1.10},
            "status": "available",
            "description": "[DEMO] Cold brew coffee 330ml can. Remove before going live.",
            "barcode": "2110010000019",
            "attributes": {"volume_ml": "330", "caffeine_mg": "150", "sugar": "0g"},
        },
        {
            "sku": "DEMO-F&B-002",
            "name": "[DEMO] Dark Chocolate Bar 72% - 100g",
            "category": "confectionery",
            "quantity": 200,
            "sell_by": "piece",
            "prices": {"Retail": 4.99, "Wholesale": 3.10, "Cost": 1.60},
            "status": "available",
            "description": "[DEMO] Dark chocolate 72% cacao 100g bar. Remove before going live.",
            "barcode": "2110020000026",
            "attributes": {"cacao_pct": "72", "weight_g": "100", "origin": "Ecuador"},
        },
        {
            "sku": "DEMO-F&B-003",
            "name": "[DEMO] Organic Pasta - Penne 500g",
            "category": "packaged_food",
            "quantity": 80,
            "sell_by": "piece",
            "prices": {"Retail": 2.99, "Wholesale": 1.80, "Cost": 0.90},
            "status": "available",
            "description": "[DEMO] Organic durum wheat penne 500g. Remove before going live.",
            "barcode": "2110030000033",
            "attributes": {"weight_g": "500", "organic": "Yes", "shape": "Penne"},
        },
        {
            "sku": "DEMO-F&B-004",
            "name": "[DEMO] Frozen Margherita Pizza - 400g",
            "category": "frozen_food",
            "quantity": 50,
            "sell_by": "piece",
            "prices": {"Retail": 6.99, "Wholesale": 4.20, "Cost": 2.20},
            "status": "available",
            "description": "[DEMO] Frozen margherita pizza 400g. Remove before going live.",
            "barcode": "2110040000040",
            "attributes": {"weight_g": "400", "diameter_cm": "30", "vegetarian": "Yes"},
        },
    ],
    "furniture": [
        {
            "sku": "DEMO-FRN-001",
            "name": "[DEMO] Ergonomic Office Chair - Black Mesh",
            "category": "seating",
            "quantity": 5,
            "sell_by": "piece",
            "prices": {"Retail": 420.00, "Wholesale": 270.00, "Cost": 145.00},
            "status": "available",
            "description": "[DEMO] Ergonomic mesh office chair with lumbar support. Remove before going live.",
            "barcode": "2120010000018",
            "attributes": {"color": "Black", "material": "Mesh/Metal", "max_load_kg": "120"},
        },
        {
            "sku": "DEMO-FRN-002",
            "name": "[DEMO] Solid Oak Dining Table - 180cm",
            "category": "table_desk",
            "quantity": 2,
            "sell_by": "piece",
            "prices": {"Retail": 1200.00, "Wholesale": 780.00, "Cost": 420.00},
            "status": "available",
            "description": "[DEMO] Solid oak dining table 180x90cm, seats 6. Remove before going live.",
            "barcode": "2120020000025",
            "attributes": {"material": "Solid Oak", "dimensions_cm": "180 x 90 x 76", "seats": "6"},
        },
        {
            "sku": "DEMO-FRN-003",
            "name": "[DEMO] 3-Door Wardrobe with Mirror - White",
            "category": "storage_furniture",
            "quantity": 2,
            "sell_by": "piece",
            "prices": {"Retail": 650.00, "Wholesale": 420.00, "Cost": 220.00},
            "status": "available",
            "description": "[DEMO] 3-door white wardrobe with central mirror. Remove before going live.",
            "barcode": "2120030000032",
            "attributes": {"color": "White", "doors": "3", "dimensions_cm": "150 x 60 x 200"},
        },
        {
            "sku": "DEMO-FRN-004",
            "name": "[DEMO] Floor Lamp - Brass Finish",
            "category": "lighting",
            "quantity": 8,
            "sell_by": "piece",
            "prices": {"Retail": 180.00, "Wholesale": 110.00, "Cost": 55.00},
            "status": "available",
            "description": "[DEMO] Arc floor lamp, brushed brass finish. Remove before going live.",
            "barcode": "2120040000049",
            "attributes": {"finish": "Brushed Brass", "height_cm": "165", "bulb": "E27 LED"},
        },
    ],
    "gemstones": [
        {
            "sku": "DEMO-DIA-001",
            "name": "[DEMO] Diamond - 1.05ct Round Brilliant",
            "category": "Diamond",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 9800.00, "Wholesale": 6500.00, "Cost": 4200.00},
            "status": "available",
            "description": "[DEMO] Example diamond sold by piece. Remove before going live.",
            "barcode": "2130010000013",
            "attributes": {
                "origin_type": "Natural",
                "grade": "F",
                "carat": "1.05",
                "cut": "Excellent",
                "clarity": "VS1",
                "shape": "Round",
                "fluorescence": "None",
                "polish": "Excellent",
                "symmetry": "Excellent",
                "measurements": "6.51 x 6.54 x 4.01",
                "certificate_no": "GIA-1234567890",
                "cert_body": "GIA",
            },
        },
        {
            "sku": "DEMO-RUB-001",
            "name": "[DEMO] Ruby - 2.30ct Oval, Pigeon Blood, Burma",
            "category": "Ruby",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 22000.00, "Wholesale": 14000.00, "Cost": 8500.00},
            "status": "available",
            "description": "[DEMO] Example ruby sold by piece. Remove before going live.",
            "barcode": "2130020000020",
            "attributes": {
                "origin": "Burma",
                "carat": "2.30",
                "color": "Pigeon Blood Red",
                "treatment": "Heat",
                "clarity": "VS2",
                "shape": "Oval",
                "measurements": "8.2 x 6.8 x 4.5",
                "certificate_no": "GRS-2024-001234",
                "cert_body": "GRS",
            },
        },
        {
            "sku": "DEMO-SAP-001",
            "name": "[DEMO] Sapphire - 3.15ct Oval, Royal Blue, Kashmir",
            "category": "Sapphire",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 34000.00, "Wholesale": 20000.00, "Cost": 12000.00},
            "status": "available",
            "description": "[DEMO] Example sapphire sold by piece. Remove before going live.",
            "barcode": "2130030000037",
            "attributes": {
                "origin": "Kashmir",
                "carat": "3.15",
                "color": "Royal Blue",
                "treatment": "No Heat",
                "clarity": "VS1",
                "shape": "Oval",
                "measurements": "9.1 x 7.4 x 5.2",
                "certificate_no": "Gubelin-2024-5678",
                "cert_body": "Gubelin",
            },
        },
        {
            "sku": "DEMO-EMR-001",
            "name": "[DEMO] Emerald - 1.82ct Oval, Vivid Green, Colombia",
            "category": "Emerald",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 15000.00, "Wholesale": 9500.00, "Cost": 5800.00},
            "status": "available",
            "description": "[DEMO] Example emerald sold by piece. Remove before going live.",
            "barcode": "2130040000044",
            "attributes": {
                "origin": "Colombia",
                "carat": "1.82",
                "color": "Vivid Green",
                "treatment": "Minor Oil",
                "clarity": "SI1",
                "shape": "Oval",
                "measurements": "8.0 x 6.2 x 4.8",
                "certificate_no": "AGL-2024-9876",
                "cert_body": "AGL",
            },
        },
        {
            "sku": "DEMO-COL-001",
            "name": "[DEMO] Spinel - 4.50ct Round, Red, Burma",
            "category": "Colored Stone",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 8500.00, "Wholesale": 5500.00, "Cost": 3200.00},
            "status": "available",
            "description": "[DEMO] Colored stone sold by piece. Remove before going live.",
            "barcode": "2130050000051",
            "attributes": {
                "stone_type": "Spinel",
                "origin": "Burma",
                "carat": "4.50",
                "color": "Red",
                "treatment": "No Heat",
                "clarity": "VS2",
                "shape": "Round",
                "measurements": "9.8 x 9.7 x 6.3",
                "certificate_no": "GIA-COL-2024-001",
                "cert_body": "GIA",
            },
        },
        {
            "sku": "DEMO-COL-002",
            "name": "[DEMO] Tourmaline Parcel - 38.60ct mixed lot",
            "category": "Colored Stone",
            "quantity": 38.60,
            "sell_by": "carat",
            "prices": {"Retail": 38.86, "Wholesale": 24.87, "Cost": 15.03},
            "status": "available",
            "description": "[DEMO] Colored stone parcel priced per carat. Remove before going live.",
            "barcode": "2130060000068",
            "attributes": {
                "stone_type": "Tourmaline",
                "origin": "Brazil",
                "color": "Green",
                "treatment": "Heat",
                "clarity": "SI2",
                "shape": "Mixed",
                "lot_ref": "LOT-TRM-2024-001",
            },
        },
        {
            "sku": "DEMO-RGH-001",
            "name": "[DEMO] Rough Ruby - 64ct parcel",
            "category": "Rough Gemstone",
            "quantity": 64.0,
            "sell_by": "carat",
            "prices": {"Retail": 17.19, "Wholesale": 10.94, "Cost": 6.56},
            "status": "available",
            "description": "[DEMO] Rough gemstone parcel priced per carat. Remove before going live.",
            "barcode": "2130070000075",
            "attributes": {
                "stone_type": "Ruby",
                "origin": "Mozambique",
                "color": "Red",
                "treatment": "None",
                "lot_ref": "LOT-RGHRU-2024-001",
            },
        },
        {
            "sku": "DEMO-MIN-001",
            "name": "[DEMO] Amethyst Cluster - Museum Grade",
            "category": "Mineral Specimen",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 550.00, "Wholesale": 320.00, "Cost": 180.00},
            "status": "available",
            "description": "[DEMO] Mineral specimen example. Remove before going live.",
            "barcode": "2130080000082",
            "attributes": {
                "mineral": "Amethyst",
                "origin": "Uruguay",
                "dimensions_cm": "18 x 12 x 10",
                "weight_g": "1850",
                "grade": "Museum",
                "condition": "Excellent",
            },
        },
        {
            "sku": "DEMO-PRL-001",
            "name": "[DEMO] South Sea Pearl Strand - 11-12mm",
            "category": "Pearl",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 7200.00, "Wholesale": 4500.00, "Cost": 2800.00},
            "status": "available",
            "description": "[DEMO] Pearl strand example. Remove before going live.",
            "barcode": "2130090000099",
            "attributes": {
                "pearl_type": "South Sea",
                "size_mm": "11-12",
                "shape": "Round",
                "color": "White",
                "luster": "High",
                "surface": "Clean",
                "nacre": "Thick",
                "strand_length": "45cm",
            },
        },
        {
            "sku": "DEMO-JWL-001",
            "name": "[DEMO] 18k White Gold Diamond Ring - 0.75ct total",
            "category": "Jewelry",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 5500.00, "Wholesale": 3200.00, "Cost": 1800.00},
            "status": "available",
            "description": "[DEMO] Jewelry example. Remove before going live.",
            "barcode": "2130100000106",
            "attributes": {
                "style": "Ring",
                "metal": "18k White Gold",
                "weight_g": "4.2",
                "stones": "0.75ct total diamond pave",
                "hallmark": "750",
                "condition": "New",
            },
        },
    ],
    "hardware": [
        {
            "sku": "DEMO-HW-001",
            "name": "[DEMO] 18V Cordless Drill/Driver Kit",
            "category": "power_tool",
            "quantity": 8,
            "sell_by": "piece",
            "prices": {"Retail": 149.00, "Wholesale": 95.00, "Cost": 52.00},
            "status": "available",
            "description": "[DEMO] 18V cordless drill/driver with 2 batteries. Remove before going live.",
            "barcode": "2140010000017",
            "attributes": {"voltage": "18V", "torque_nm": "50", "battery": "2x 2.0Ah Li-Ion"},
        },
        {
            "sku": "DEMO-HW-002",
            "name": "[DEMO] M8 Hex Bolts Stainless - Box of 100",
            "category": "fastener",
            "quantity": 50,
            "sell_by": "piece",
            "prices": {"Retail": 18.00, "Wholesale": 11.00, "Cost": 5.50},
            "status": "available",
            "description": "[DEMO] M8 x 40mm stainless hex bolts, box of 100. Remove before going live.",
            "barcode": "2140020000024",
            "attributes": {"size": "M8 x 40mm", "material": "A2 Stainless", "qty_per_box": "100"},
        },
        {
            "sku": "DEMO-HW-003",
            "name": "[DEMO] Digital Vernier Caliper - 150mm",
            "category": "measuring_instrument",
            "quantity": 15,
            "sell_by": "piece",
            "prices": {"Retail": 35.00, "Wholesale": 22.00, "Cost": 11.00},
            "status": "available",
            "description": "[DEMO] Digital vernier caliper 0-150mm, 0.01mm resolution. Remove before going live.",
            "barcode": "2140030000031",
            "attributes": {"range_mm": "0-150", "resolution_mm": "0.01", "display": "Digital LCD"},
        },
        {
            "sku": "DEMO-HW-004",
            "name": "[DEMO] Safety Hard Hat - Class E White",
            "category": "safety_ppe",
            "quantity": 25,
            "sell_by": "piece",
            "prices": {"Retail": 22.00, "Wholesale": 13.00, "Cost": 6.00},
            "status": "available",
            "description": "[DEMO] Class E adjustable safety hard hat, white. Remove before going live.",
            "barcode": "2140040000048",
            "attributes": {"class": "E", "color": "White", "standard": "ANSI Z89.1"},
        },
    ],
    "property_rental": [
        {
            "sku": "DEMO-PROP-001",
            "name": "[DEMO] 2-Bedroom Apartment - Monthly Rental",
            "category": "residential_unit",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 2500.00, "Wholesale": 2200.00, "Cost": 1200.00},
            "status": "available",
            "description": "[DEMO] 2-bed apartment monthly rental. Remove before going live.",
            "barcode": "2150010000016",
            "attributes": {"bedrooms": "2", "size_sqm": "75", "floor": "4"},
        },
        {
            "sku": "DEMO-PROP-002",
            "name": "[DEMO] Office Space - 50sqm Monthly",
            "category": "commercial_space",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 3200.00, "Wholesale": 2800.00, "Cost": 1800.00},
            "status": "available",
            "description": "[DEMO] Commercial office space 50sqm monthly. Remove before going live.",
            "barcode": "2150020000023",
            "attributes": {"size_sqm": "50", "floor": "2", "furnished": "Yes"},
        },
        {
            "sku": "DEMO-PROP-003",
            "name": "[DEMO] Covered Parking Bay - Monthly",
            "category": "parking_bay",
            "quantity": 3,
            "sell_by": "piece",
            "prices": {"Retail": 150.00, "Wholesale": 120.00, "Cost": 60.00},
            "status": "available",
            "description": "[DEMO] Covered parking bay monthly rental. Remove before going live.",
            "barcode": "2150030000030",
            "attributes": {"type": "Covered", "size": "Standard", "access": "24/7"},
        },
    ],
    "saas": [
        {
            "sku": "DEMO-SAAS-001",
            "name": "[DEMO] Starter Plan - Monthly Subscription",
            "category": "saas_plan",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 29.00, "Wholesale": 22.00, "Cost": 5.00},
            "status": "available",
            "description": "[DEMO] Starter SaaS plan, up to 5 users. Remove before going live.",
            "barcode": "2160010000015",
            "attributes": {"users": "5", "billing": "Monthly", "support": "Email"},
        },
        {
            "sku": "DEMO-SAAS-002",
            "name": "[DEMO] Professional Plan - Annual Subscription",
            "category": "saas_plan",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 990.00, "Wholesale": 750.00, "Cost": 120.00},
            "status": "available",
            "description": "[DEMO] Professional plan annual, up to 25 users. Remove before going live.",
            "barcode": "2160020000022",
            "attributes": {"users": "25", "billing": "Annual", "support": "Priority"},
        },
        {
            "sku": "DEMO-SAAS-003",
            "name": "[DEMO] API Add-On - 1M Calls/Month",
            "category": "software_addon",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 49.00, "Wholesale": 38.00, "Cost": 8.00},
            "status": "available",
            "description": "[DEMO] API add-on, 1 million calls per month. Remove before going live.",
            "barcode": "2160030000039",
            "attributes": {"calls_per_month": "1,000,000", "billing": "Monthly", "overage": "Per 1k calls"},
        },
    ],
    "watches": [
        {
            "sku": "DEMO-WCH-001",
            "name": "[DEMO] Swiss Automatic Watch - 40mm Steel",
            "category": "watch",
            "quantity": 2,
            "sell_by": "piece",
            "prices": {"Retail": 3800.00, "Wholesale": 2500.00, "Cost": 1400.00},
            "status": "available",
            "description": "[DEMO] Swiss automatic movement, 40mm stainless steel. Remove before going live.",
            "barcode": "2170010000014",
            "attributes": {"movement": "Swiss Automatic", "case_mm": "40", "water_resist_m": "100"},
        },
        {
            "sku": "DEMO-WCH-002",
            "name": "[DEMO] Leather Watch Strap - 20mm Brown",
            "category": "watch_strap",
            "quantity": 20,
            "sell_by": "piece",
            "prices": {"Retail": 85.00, "Wholesale": 52.00, "Cost": 22.00},
            "status": "available",
            "description": "[DEMO] 20mm genuine leather watch strap, brown. Remove before going live.",
            "barcode": "2170020000021",
            "attributes": {"width_mm": "20", "color": "Brown", "material": "Genuine Leather"},
        },
        {
            "sku": "DEMO-WCH-003",
            "name": "[DEMO] Luxury Fountain Pen - 18k Gold Nib",
            "category": "fine_writing_instrument",
            "quantity": 3,
            "sell_by": "piece",
            "prices": {"Retail": 650.00, "Wholesale": 420.00, "Cost": 200.00},
            "status": "available",
            "description": "[DEMO] Luxury fountain pen with 18k gold nib. Remove before going live.",
            "barcode": "2170030000038",
            "attributes": {"nib_material": "18k Gold", "nib_size": "Medium", "filling": "Cartridge/Converter"},
        },
        {
            "sku": "DEMO-WCH-004",
            "name": "[DEMO] Diamond Bracelet - 18k White Gold",
            "category": "jewelry",
            "quantity": 1,
            "sell_by": "piece",
            "prices": {"Retail": 4200.00, "Wholesale": 2800.00, "Cost": 1500.00},
            "status": "available",
            "description": "[DEMO] 18k white gold diamond tennis bracelet. Remove before going live.",
            "barcode": "2170040000045",
            "attributes": {"metal": "18k White Gold", "total_ct": "2.0", "length_cm": "18"},
        },
    ],
    "wine_spirits": [
        {
            "sku": "DEMO-W&S-001",
            "name": "[DEMO] Bordeaux Rouge - 750ml Bottle",
            "category": "wine",
            "quantity": 24,
            "sell_by": "piece",
            "prices": {"Retail": 28.00, "Wholesale": 18.00, "Cost": 10.00},
            "status": "available",
            "description": "[DEMO] Bordeaux red wine, 750ml bottle. Remove before going live.",
            "barcode": "2180010000018",
            "attributes": {"type": "Red", "region": "Bordeaux, France", "vintage": "2021"},
        },
        {
            "sku": "DEMO-W&S-002",
            "name": "[DEMO] Single Malt Scotch Whisky 12yr - 700ml",
            "category": "spirit",
            "quantity": 12,
            "sell_by": "piece",
            "prices": {"Retail": 65.00, "Wholesale": 42.00, "Cost": 25.00},
            "status": "available",
            "description": "[DEMO] 12-year single malt Scotch whisky 700ml. Remove before going live.",
            "barcode": "2180020000025",
            "attributes": {"age_years": "12", "region": "Speyside, Scotland", "abv_pct": "43"},
        },
        {
            "sku": "DEMO-W&S-003",
            "name": "[DEMO] Craft IPA Beer - 330ml Can x24",
            "category": "beer",
            "quantity": 20,
            "sell_by": "piece",
            "prices": {"Retail": 38.00, "Wholesale": 24.00, "Cost": 13.00},
            "status": "available",
            "description": "[DEMO] Craft IPA beer 330ml cans, 24-pack. Remove before going live.",
            "barcode": "2180030000032",
            "attributes": {"style": "IPA", "abv_pct": "6.5", "cans_per_case": "24"},
        },
        {
            "sku": "DEMO-W&S-004",
            "name": "[DEMO] Champagne Brut NV - 750ml",
            "category": "wine",
            "quantity": 6,
            "sell_by": "piece",
            "prices": {"Retail": 55.00, "Wholesale": 36.00, "Cost": 22.00},
            "status": "available",
            "description": "[DEMO] Non-vintage Brut Champagne 750ml. Remove before going live.",
            "barcode": "2180040000049",
            "attributes": {"type": "Sparkling", "region": "Champagne, France", "dosage": "Brut"},
        },
    ],
}


# --- Default payment terms (used when no vertical match) ---
_DEFAULT_PAYMENT_TERMS: list[dict] = [
    {"name": "Pay in Advance", "days": 0, "description": "Full payment before delivery"},
    {"name": "Cash on Delivery", "days": 0, "description": "Payment on receipt of goods"},
    {"name": "Deposit (50%)", "days": 0, "description": "50% deposit upfront, balance on delivery"},
    {"name": "Net 7", "days": 7, "description": "Due within 7 days"},
    {"name": "Net 15", "days": 15, "description": "Due within 15 days"},
    {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
    {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
]

# Industry-specific payment terms
_VERTICAL_PAYMENT_TERMS: dict[str, list[dict]] = {
    "gemstones": [
        {"name": "Pay in Advance", "days": 0, "description": "Full payment before shipment"},
        {"name": "Deposit (50%)", "days": 0, "description": "50% deposit, balance on delivery"},
        {"name": "Cash on Delivery", "days": 0, "description": "Payment on receipt"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
        {"name": "Consignment 90", "days": 90, "description": "Consignment terms, settle within 90 days"},
    ],
    "jewelry": [
        {"name": "Pay in Advance", "days": 0, "description": "Full payment before production"},
        {"name": "Deposit (50%)", "days": 0, "description": "50% deposit, balance on completion"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
        {"name": "Consignment 60", "days": 60, "description": "Consignment, settle within 60 days"},
    ],
    "food_beverage": [
        {"name": "Pay in Advance", "days": 0, "description": "Prepayment required"},
        {"name": "Cash on Delivery", "days": 0, "description": "Payment on receipt"},
        {"name": "Net 7", "days": 7, "description": "Due within 7 days"},
        {"name": "Net 14", "days": 14, "description": "Due within 14 days"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
    ],
    "construction": [
        {"name": "Deposit (30%)", "days": 0, "description": "30% deposit on order"},
        {"name": "Deposit (50%)", "days": 0, "description": "50% deposit on order"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 45", "days": 45, "description": "Due within 45 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
        {"name": "Net 90", "days": 90, "description": "Due within 90 days"},
    ],
    "agriculture": [
        {"name": "Pay in Advance", "days": 0, "description": "Prepayment for seasonal goods"},
        {"name": "Cash on Delivery", "days": 0, "description": "Payment at harvest/delivery"},
        {"name": "Net 14", "days": 14, "description": "Due within 14 days"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 60", "days": 60, "description": "Seasonal credit terms"},
    ],
    "automotive": [
        {"name": "Pay in Advance", "days": 0, "description": "Prepayment on order"},
        {"name": "Deposit (50%)", "days": 0, "description": "50% deposit, balance on delivery"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 45", "days": 45, "description": "Due within 45 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
    ],
    "electronics": [
        {"name": "Pay in Advance", "days": 0, "description": "Prepayment required"},
        {"name": "Net 15", "days": 15, "description": "Due within 15 days"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 45", "days": 45, "description": "Due within 45 days"},
    ],
    "fashion": [
        {"name": "Pay in Advance", "days": 0, "description": "Prepayment on order"},
        {"name": "Deposit (50%)", "days": 0, "description": "50% deposit, balance on shipment"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
        {"name": "Consignment 60", "days": 60, "description": "Consignment, settle within 60 days"},
    ],
    "pharmaceuticals": [
        {"name": "Pay in Advance", "days": 0, "description": "Prepayment required"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 45", "days": 45, "description": "Due within 45 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
    ],
    "hardware": [
        {"name": "Cash on Delivery", "days": 0, "description": "Payment on receipt"},
        {"name": "Net 15", "days": 15, "description": "Due within 15 days"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
    ],
    "chemicals": [
        {"name": "Pay in Advance", "days": 0, "description": "Prepayment for hazmat shipments"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 45", "days": 45, "description": "Due within 45 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
    ],
    "medical_devices": [
        {"name": "Deposit (50%)", "days": 0, "description": "50% deposit on order"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 45", "days": 45, "description": "Due within 45 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
        {"name": "Net 90", "days": 90, "description": "Hospital/institution terms"},
    ],
    "general_trading": [
        {"name": "Pay in Advance", "days": 0, "description": "Prepayment required"},
        {"name": "Cash on Delivery", "days": 0, "description": "Payment on receipt"},
        {"name": "Net 15", "days": 15, "description": "Due within 15 days"},
        {"name": "Net 30", "days": 30, "description": "Due within 30 days"},
        {"name": "Net 60", "days": 60, "description": "Due within 60 days"},
    ],
}

# --- Default T&C templates ---
_DEFAULT_TERMS_CONDITIONS: list[dict] = [
    {"name": "Standard Sales Terms", "text": "Goods remain property of the seller until paid in full.", "doc_types": ["invoice", "receipt", "credit_note"], "default_for": ["invoice", "receipt", "credit_note"]},
    {"name": "Standard Consignment Out Terms", "text": "Consigned goods remain property of the consignor until sold or returned.", "doc_types": ["memo"], "default_for": ["memo"]},
    {"name": "Standard Purchase Terms", "text": "Goods must conform to agreed specifications.", "doc_types": ["purchase_order", "bill"], "default_for": ["purchase_order", "bill"]},
    {"name": "Standard Consignment In Terms", "text": "Consigned goods remain property of the consignor. Unsold goods may be returned per agreed schedule.", "doc_types": ["consignment_in"], "default_for": ["consignment_in"]},
]

# Industry-specific T&C templates (verticals without a specific entry use defaults)
_VERTICAL_TERMS_CONDITIONS: dict[str, list[dict]] = {
    "gemstones": [
        {"name": "Gemstone Sales Terms", "text": "All gemstones sold as described. Certification documents provided where applicable.", "doc_types": ["invoice", "receipt", "credit_note"], "default_for": ["invoice", "receipt", "credit_note"]},
        {"name": "Gemstone Consignment Out Terms", "text": "Consigned stones remain property of the consignor. Must be stored in a secure facility. Insurance is the consignee's responsibility.", "doc_types": ["memo"], "default_for": ["memo"]},
        {"name": "Gemstone Consignment In Terms", "text": "Consigned stones remain property of the consignor. Settlement within agreed terms or return of goods.", "doc_types": ["consignment_in"], "default_for": ["consignment_in"]},
        {"name": "Gemstone Purchase Terms", "text": "Stones must match the agreed grade, weight, and certification.", "doc_types": ["purchase_order", "bill"], "default_for": ["purchase_order", "bill"]},
    ],
    "jewelry": [
        {"name": "Jewelry Sales Terms", "text": "All jewelry sold as described with applicable hallmarks.", "doc_types": ["invoice", "receipt", "credit_note"], "default_for": ["invoice", "receipt", "credit_note"]},
        {"name": "Jewelry Consignment Out Terms", "text": "Consigned pieces remain property of the consignor. Insurance is the consignee's responsibility.", "doc_types": ["memo"], "default_for": ["memo"]},
        {"name": "Jewelry Consignment In Terms", "text": "Consigned pieces remain property of the consignor. Settlement on sold items per agreed schedule.", "doc_types": ["consignment_in"], "default_for": ["consignment_in"]},
    ],
    "food_beverage": [
        {"name": "F&B Sales Terms", "text": "All products sold meet applicable food safety standards.", "doc_types": ["invoice", "receipt", "credit_note"], "default_for": ["invoice", "receipt", "credit_note"]},
        {"name": "F&B Purchase Terms", "text": "Products must meet agreed quality and safety standards.", "doc_types": ["purchase_order", "bill"], "default_for": ["purchase_order", "bill"]},
    ],
    "construction": [
        {"name": "Construction Sales Terms", "text": "Materials supplied as specified per contract.", "doc_types": ["invoice", "receipt", "credit_note"], "default_for": ["invoice", "receipt", "credit_note"]},
        {"name": "Construction Purchase Terms", "text": "Materials must meet project specifications and applicable building codes.", "doc_types": ["purchase_order", "bill"], "default_for": ["purchase_order", "bill"]},
    ],
}


async def seed_demo_items(
    session: AsyncSession,
    company_id: uuid.UUID,
    actor_id: uuid.UUID,
    vertical: str | None = None,
) -> None:
    """Seed vertical-aware demo items and default price lists in company settings."""
    from celerp.models.company import Company

    # Seed default price lists into company settings if not already set
    company = await session.get(Company, company_id)
    if company is not None:
        settings = dict(company.settings or {})
        if "price_lists" not in settings:
            settings["price_lists"] = [
                {"name": "Retail", "description": "Standard retail price"},
                {"name": "Wholesale", "description": "Wholesale / trade price"},
                {"name": "Cost", "description": "Cost / landed price"},
            ]
        if "default_price_list" not in settings:
            settings["default_price_list"] = "Retail"
        # Seed payment terms if not already set
        if "payment_terms" not in settings:
            settings["payment_terms"] = _VERTICAL_PAYMENT_TERMS.get(vertical or "", _DEFAULT_PAYMENT_TERMS)
        # Seed T&C templates if not already set
        if "terms_conditions" not in settings:
            settings["terms_conditions"] = _VERTICAL_TERMS_CONDITIONS.get(vertical or "", _DEFAULT_TERMS_CONDITIONS)
        company.settings = settings
    items = _VERTICAL_ITEMS.get(vertical or "", _GENERIC_ITEMS) if vertical else _GENERIC_ITEMS
    for i, data in enumerate(items, start=1):
        entity_id = f"item:demo-{uuid.uuid4()}"
        sku = data.get("sku", f"DEMO-{i:03d}")
        # Include prices in attributes so they land in the projection state
        # even when the inventory module's projection handler isn't loaded yet
        # (setup wizard calls reseed before the API restart that loads modules).
        # _flatten_item() promotes attributes to top-level, so the API returns
        # them as retail_price, wholesale_price, cost_price at the item root.
        prices = data.get("prices") or {}
        price_attrs = {
            f"{pl_name.lower()}_price": float(pv)
            for pl_name, pv in prices.items()
            if pv is not None
        }
        item_attrs = {**data.get("attributes", {}), **price_attrs}
        payload = {
            "sku": sku,
            "name": data.get("name", f"[DEMO] Item {i}"),
            "category": data.get("category", "General"),
            "quantity": data.get("quantity", 1),
            "status": data.get("status", "available"),
            "sell_by": data.get("sell_by"),
            "weight": data.get("weight"),
            "weight_unit": data.get("weight_unit"),
            "description": data.get("description", ""),
            "barcode": data.get("barcode"),
            "attributes": item_attrs,
        }
        # Strip None values to keep event data clean
        payload = {k: v for k, v in payload.items() if v is not None}
        await emit_event(
            session,
            company_id=company_id,
            entity_id=entity_id,
            entity_type="item",
            event_type="item.created",
            data=payload,
            actor_id=actor_id,
            location_id=None,
            source="demo",
            idempotency_key=f"demo:item:{company_id}:{sku}",
        )
        # Prices are included directly in item.created above so they land in the
        # projection state regardless of whether the inventory module's handler
        # is loaded (setup wizard calls reseed before the API restart).
        # Separate item.pricing.set events are NOT emitted for demo items to
        # avoid duplicate/conflicting state when the handler isn't available.
